param(
    [string]$TempleOS,
    [string]$LoseThos,
    [string]$OutRoot = "third_party/source",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Assert-SourceDir {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        Write-Error "missing ${Name} source directory: $Path"
        exit 1
    }
}

function Copy-Snapshot {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,

        [Parameter(Mandatory = $true)]
        [string]$Source,

        [Parameter(Mandatory = $true)]
        [string]$Dest
    )

    Assert-SourceDir -Path $Source -Name $Name

    if ((Test-Path -LiteralPath $Dest) -and -not $Force) {
        Write-Error "destination already exists: $Dest; pass -Force to replace it"
        exit 1
    }

    if (Test-Path -LiteralPath $Dest) {
        Remove-Item -LiteralPath $Dest -Recurse -Force
    }

    New-Item -ItemType Directory -Force (Split-Path -Parent $Dest) | Out-Null

    $excludeDirs = @(".git", ".svn", ".hg", "target", "dist", "build", "obj", "bin")
    $excludeFiles = @("*.zip", "*.7z", "*.rar", "*.tar", "*.gz", "*.iso", "*.img", "*.vhd", "*.vdi", "*.exe", "*.dll", "*.obj", "*.pdb")

    robocopy $Source $Dest /E /NFL /NDL /NJH /NJS /NP /XD $excludeDirs /XF $excludeFiles | Out-Null
    $code = $LASTEXITCODE
    if ($code -ge 8) {
        Write-Error "robocopy failed for ${Name} with code $code"
        exit $code
    }

    Write-Host "imported ${Name}: $Dest"
}

function Count-Files {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) { return 0 }
    return @((Get-ChildItem -LiteralPath $Path -Recurse -File -ErrorAction SilentlyContinue)).Count
}

if (-not $TempleOS -and -not $LoseThos) {
    Write-Error "provide -TempleOS, -LoseThos, or both"
    exit 1
}

New-Item -ItemType Directory -Force $OutRoot | Out-Null

$metadata = @()
$metadata += "# Third-Party Source Snapshot"
$metadata += ""
$metadata += "Generated by scripts/import-third-party-sources.ps1."
$metadata += ""
$metadata += "Boundary: imported source trees are research inputs. Do not rewrite, format, compile, execute, or mutate them as DBYTE HOLYC TOOLS project source."
$metadata += ""

if ($TempleOS) {
    $dest = Join-Path $OutRoot "templeos"
    Copy-Snapshot -Name "TempleOS" -Source $TempleOS -Dest $dest
    $metadata += "## TempleOS"
    $metadata += ""
    $metadata += "Source path: `$TempleOS`"
    $metadata += "Snapshot path: `$dest`"
    $metadata += "Files: $(Count-Files $dest)"
    $metadata += ""
}

if ($LoseThos) {
    $dest = Join-Path $OutRoot "losethos"
    Copy-Snapshot -Name "LoseThos" -Source $LoseThos -Dest $dest
    $metadata += "## LoseThos"
    $metadata += ""
    $metadata += "Source path: `$LoseThos`"
    $metadata += "Snapshot path: `$dest`"
    $metadata += "Files: $(Count-Files $dest)"
    $metadata += ""
}

$metadata += "## Notes"
$metadata += ""
$metadata += "Review licensing/source provenance before pushing public snapshots."
$metadata += "Generated reports should remain separate from source snapshots unless intentionally archived."

$metadata | Set-Content -Encoding utf8 (Join-Path "third_party" "SOURCE-SNAPSHOT.md")
Write-Host "snapshot metadata: third_party/SOURCE-SNAPSHOT.md"
Write-Host "review with: git status --short"
