param(
    [string]$TempleOS,
    [string]$LoseThos,
    [string]$SparrowOS,
    [string]$OutRoot = "third_party/source",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Assert-SourceDir {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        Write-Error "missing ${Name} source directory: $Path"
        exit 1
    }
}

function Copy-Snapshot {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,
        [Parameter(Mandatory = $true)]
        [string]$Source,
        [Parameter(Mandatory = $true)]
        [string]$Dest
    )

    Assert-SourceDir -Path $Source -Name $Name

    if ((Test-Path -LiteralPath $Dest) -and -not $Force) {
        Write-Error "destination already exists: $Dest; pass -Force to replace it"
        exit 1
    }

    if (Test-Path -LiteralPath $Dest) {
        Remove-Item -LiteralPath $Dest -Recurse -Force
    }

    New-Item -ItemType Directory -Force (Split-Path -Parent $Dest) | Out-Null
    $excludeDirs = @(".git", ".svn", ".hg", "target", "dist", "build", "obj", "bin")
    $excludeFiles = @("*.zip", "*.7z", "*.rar", "*.tar", "*.gz", "*.iso", "*.img", "*.vhd", "*.vdi", "*.exe", "*.dll", "*.obj", "*.pdb")

    robocopy $Source $Dest /E /NFL /NDL /NJH /NJS /NP /XD $excludeDirs /XF $excludeFiles | Out-Null
    $code = $LASTEXITCODE
    if ($code -ge 8) {
        Write-Error "robocopy failed for ${Name} with code $code"
        exit $code
    }

    Write-Host "imported ${Name}: $Dest"
}

function Count-Files {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) { return 0 }
    return @((Get-ChildItem -LiteralPath $Path -Recurse -File -ErrorAction SilentlyContinue)).Count
}

function Add-SnapshotMetadata {
    param(
        [Parameter(Mandatory = $true)]
        [System.Collections.ArrayList]$Metadata,
        [Parameter(Mandatory = $true)]
        [string]$Title,
        [Parameter(Mandatory = $true)]
        [string]$Source,
        [Parameter(Mandatory = $true)]
        [string]$Dest
    )

    [void]$Metadata.Add("## $Title")
    [void]$Metadata.Add("")
    [void]$Metadata.Add(("Source path: {0}" -f $Source))
    [void]$Metadata.Add(("Snapshot path: {0}" -f $Dest))
    [void]$Metadata.Add("Files: $(Count-Files $Dest)")
    [void]$Metadata.Add("")
}

if (-not $TempleOS -and -not $LoseThos -and -not $SparrowOS) {
    Write-Error "provide -TempleOS, -LoseThos, -SparrowOS, or any combination"
    exit 1
}

New-Item -ItemType Directory -Force $OutRoot | Out-Null

$metadata = [System.Collections.ArrayList]::new()
[void]$metadata.Add("# Third-Party Source Snapshot")
[void]$metadata.Add("")
[void]$metadata.Add("Generated by scripts/import-third-party-sources.ps1.")
[void]$metadata.Add("")
[void]$metadata.Add("Boundary: imported source trees are research inputs for DBYTE HOLYC TOOLS.")
[void]$metadata.Add("")

$templeDest = Join-Path $OutRoot "templeos"
$losethosDest = Join-Path $OutRoot "losethos"
$sparrowDest = Join-Path $OutRoot "sparrowos"

if ($TempleOS) {
    Copy-Snapshot -Name "TempleOS" -Source $TempleOS -Dest $templeDest
    Add-SnapshotMetadata -Metadata $metadata -Title "TempleOS" -Source $TempleOS -Dest $templeDest
} elseif (Test-Path -LiteralPath $templeDest -PathType Container) {
    Add-SnapshotMetadata -Metadata $metadata -Title "TempleOS" -Source "existing snapshot" -Dest $templeDest
}

if ($LoseThos) {
    Copy-Snapshot -Name "LoseThos" -Source $LoseThos -Dest $losethosDest
    Add-SnapshotMetadata -Metadata $metadata -Title "LoseThos" -Source $LoseThos -Dest $losethosDest
} elseif (Test-Path -LiteralPath $losethosDest -PathType Container) {
    Add-SnapshotMetadata -Metadata $metadata -Title "LoseThos" -Source "existing snapshot" -Dest $losethosDest
}

if ($SparrowOS) {
    Copy-Snapshot -Name "SparrowOS" -Source $SparrowOS -Dest $sparrowDest
    Add-SnapshotMetadata -Metadata $metadata -Title "SparrowOS" -Source $SparrowOS -Dest $sparrowDest
} elseif (Test-Path -LiteralPath $sparrowDest -PathType Container) {
    Add-SnapshotMetadata -Metadata $metadata -Title "SparrowOS" -Source "existing snapshot" -Dest $sparrowDest
}

[void]$metadata.Add("## Notes")
[void]$metadata.Add("")
[void]$metadata.Add("Review licensing and source provenance before pushing public snapshots.")
[void]$metadata.Add("Generated reports should remain separate from source snapshots unless intentionally archived.")

$metadata | Set-Content -Encoding utf8 (Join-Path "third_party" "SOURCE-SNAPSHOT.md")
Write-Host "snapshot metadata: third_party/SOURCE-SNAPSHOT.md"
Write-Host "review with: git status --short"
