param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$snapshots = @(
    @{ name = "TempleOS"; old = "third_party/source/templeos"; new = "templeos" },
    @{ name = "LoseThos"; old = "third_party/source/losethos"; new = "losethos" },
    @{ name = "SparrowOS"; old = "third_party/source/sparrowos"; new = "sparrowos" }
)

function Count-Files {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) { return 0 }
    return @((Get-ChildItem -LiteralPath $Path -Recurse -File -ErrorAction SilentlyContinue)).Count
}

function Invoke-GitMv {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Old,
        [Parameter(Mandatory = $true)]
        [string]$New,
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    if (-not (Test-Path -LiteralPath $Old -PathType Container)) {
        if (Test-Path -LiteralPath $New -PathType Container) {
            Write-Host "already at root: ${Name} -> $New"
            return
        }
        Write-Error "missing source snapshot for ${Name}: $Old"
        exit 1
    }

    if (Test-Path -LiteralPath $New) {
        if (-not $Force) {
            Write-Error "destination already exists: $New; pass -Force to replace it"
            exit 1
        }
        Remove-Item -LiteralPath $New -Recurse -Force
    }

    git mv $Old $New
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Host "moved ${Name}: $Old -> $New"
}

foreach ($snapshot in $snapshots) {
    Invoke-GitMv -Old $snapshot.old -New $snapshot.new -Name $snapshot.name
}

$metadata = [System.Collections.ArrayList]::new()
[void]$metadata.Add("# Source Snapshots")
[void]$metadata.Add("")
[void]$metadata.Add("Generated by scripts/move-source-snapshots-to-root.ps1.")
[void]$metadata.Add("")
[void]$metadata.Add("Boundary: imported source trees are research inputs for DBYTE HOLYC TOOLS.")
[void]$metadata.Add("Do not rewrite, format, compile, execute, or mutate them as project-owned source.")
[void]$metadata.Add("")

foreach ($snapshot in $snapshots) {
    $path = $snapshot.new
    [void]$metadata.Add("## $($snapshot.name)")
    [void]$metadata.Add("")
    [void]$metadata.Add("Snapshot path: $path")
    [void]$metadata.Add("Files: $(Count-Files $path)")
    [void]$metadata.Add("")
}

[void]$metadata.Add("## Notes")
[void]$metadata.Add("")
[void]$metadata.Add("Root layout is intentional: templeos/, losethos/, and sparrowos/ live at repository root as archival research snapshots.")
[void]$metadata.Add("Generated reports remain under reports/archaeology/.")

$metadata | Set-Content -Encoding utf8 "SOURCE-SNAPSHOTS.md"

if (Test-Path -LiteralPath "third_party/SOURCE-SNAPSHOT.md" -PathType Leaf) {
    git rm "third_party/SOURCE-SNAPSHOT.md"
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

Write-Host "snapshot metadata: SOURCE-SNAPSHOTS.md"
Write-Host "review with: git status --short"
