name: verify

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: rust version
        run: rustc --version

      - name: cargo version
        run: cargo --version

      - name: verify
        shell: pwsh
        run: ./scripts/verify.ps1
